name: Lint Code Base

on:
  pull_request:
    # This will trigger the workflow for pull requests to any branch
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify your Node.js version here

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint
        continue-on-error: false
